# Generated by Django 4.1.4 on 2023-01-05 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_id', to='accounts.userdisplayname')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdisplayname')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contacts',
            constraint=models.UniqueConstraint(fields=('requester', 'addressee'), name='unique_friendship'),
        ),
    ]
