# Generated by Django 4.1.4 on 2023-01-05 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('startDate', models.CharField(max_length=64)),
                ('endDate', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdisplayname')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdisplayname')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userevents',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event'),
        ),
        migrations.AddConstraint(
            model_name='events',
            constraint=models.UniqueConstraint(fields=('name', 'creator', 'startDate', 'endDate'), name='unique_event'),
        ),
    ]
