# Generated by Django 4.1.4 on 2023-01-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_key',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
    ]
