# Generated by Django 4.1.4 on 2023-01-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
