# Generated by Django 4.1.4 on 2023-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='challenge',
            field=models.IntegerField(default=None),
        ),
    ]
