# Generated by Django 4.1.4 on 2023-01-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tag',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
