# Generated by Django 4.1.4 on 2023-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nonce',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
