# Generated by Django 4.1.4 on 2023-01-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
