# Generated by Django 4.1.4 on 2023-01-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.TextField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.TextField(max_length=1024, unique=True),
        ),
    ]
