# Generated by Django 4.1.4 on 2023-01-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nonce',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='private_key',
            field=models.TextField(max_length=500000, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='public_key',
            field=models.TextField(max_length=500000, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tag',
            field=models.CharField(default=None, max_length=1000000),
        ),
    ]
