# Generated by Django 4.1.4 on 2023-01-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='challenge',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nonce',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tag',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
