# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/FichierUi/connexion.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 550)
        Dialog.setMinimumSize(QtCore.QSize(550, 550))
        Dialog.setMaximumSize(QtCore.QSize(550, 550))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setModal(False)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 531, 91))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 120, 461, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(20)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditSecretstring = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditSecretstring.setText("")
        self.lineEditSecretstring.setMaxLength(20)
        self.lineEditSecretstring.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditSecretstring.setObjectName("lineEditSecretstring")
        self.gridLayout.addWidget(self.lineEditSecretstring, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(230, 310, 91, 25))
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(180, 360, 187, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayoutRegister = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayoutRegister.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutRegister.setObjectName("gridLayoutRegister")
        self.labelRegister = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelRegister.setObjectName("labelRegister")
        self.gridLayoutRegister.addWidget(self.labelRegister, 0, 0, 1, 1)
        self.pushButtonRegister = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.gridLayoutRegister.addWidget(self.pushButtonRegister, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Agenda"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.label_2.setText(_translate("Dialog", "Username"))
        self.label_4.setText(_translate("Dialog", "Secret string"))
        self.pushButton.setText(_translate("Dialog", "Connexion"))
        self.labelRegister.setText(_translate("Dialog", "No account ?"))
        self.pushButtonRegister.setText(_translate("Dialog", "Register"))
