# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/FichierUi/invaliddisplayname.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_invaliddisplayname(object):
    def setupUi(self, invaliddisplayname):
        invaliddisplayname.setObjectName("invaliddisplayname")
        invaliddisplayname.resize(320, 240)
        self.textBrowser = QtWidgets.QTextBrowser(invaliddisplayname)
        self.textBrowser.setGeometry(QtCore.QRect(20, 50, 261, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.buttonBox = QtWidgets.QDialogButtonBox(invaliddisplayname)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(220, 170, 81, 25))
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Belgium))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(invaliddisplayname)
        QtCore.QMetaObject.connectSlotsByName(invaliddisplayname)

    def retranslateUi(self, invaliddisplayname):
        _translate = QtCore.QCoreApplication.translate
        invaliddisplayname.setWindowTitle(_translate("invaliddisplayname", "Dialog"))
        self.textBrowser.setHtml(_translate("invaliddisplayname", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Invalid displayname use only lowercase, uppercase and numbers. Use at least 4 characters</span></p></body></html>"))
