# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/FichierUi/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 550)
        Dialog.setMinimumSize(QtCore.QSize(550, 550))
        Dialog.setMaximumSize(QtCore.QSize(550, 550))
        Dialog.setModal(True)
        self.pushButtonValide = QtWidgets.QPushButton(Dialog)
        self.pushButtonValide.setGeometry(QtCore.QRect(380, 360, 111, 25))
        self.pushButtonValide.setObjectName("pushButtonValide")
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(10, 69, 531, 71))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 180, 421, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditPassword = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditPassword.setMaxLength(20)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 3, 1, 1, 1)
        self.lineEditLoginname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditLoginname.setMaxLength(10)
        self.lineEditLoginname.setObjectName("lineEditLoginname")
        self.gridLayout.addWidget(self.lineEditLoginname, 1, 1, 1, 1)
        self.labelPassword = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 3, 0, 1, 1)
        self.labelUsername = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout.addWidget(self.labelUsername, 1, 0, 1, 1)
        self.labelDisplayname = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelDisplayname.setObjectName("labelDisplayname")
        self.gridLayout.addWidget(self.labelDisplayname, 0, 0, 1, 1)
        self.lineEdiDisplayname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdiDisplayname.setMaxLength(10)
        self.lineEdiDisplayname.setObjectName("lineEdiDisplayname")
        self.gridLayout.addWidget(self.lineEdiDisplayname, 0, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(70, 340, 291, 151))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonValide.setText(_translate("Dialog", "Valide"))
        self.labelTitle.setText(_translate("Dialog", "Create your account"))
        self.labelPassword.setText(_translate("Dialog", "Password"))
        self.labelUsername.setText(_translate("Dialog", "Login name"))
        self.labelDisplayname.setText(_translate("Dialog", "Display name"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Your password must contain only lowercase, uppercase and special characters (from this list &quot;?&quot;, &quot;!&quot;, &quot;_&quot;, &quot;+&quot;, &quot;/&quot; and &quot;@&quot;). Your password must contain at least 8 characters, one uppercase, one lowercase, one number and one special characters (from this list &quot;?&quot;, &quot;!&quot;, &quot;_&quot;, &quot;+&quot;, &quot;/&quot; and &quot;@&quot;).</p></body></html>"))
