# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ubuntu/FichierUi/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 670)
        Dialog.setMinimumSize(QtCore.QSize(900, 670))
        Dialog.setMaximumSize(QtCore.QSize(900, 670))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 170, 801, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonModifyDisplayname = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonModifyDisplayname.setEnabled(False)
        self.pushButtonModifyDisplayname.setObjectName("pushButtonModifyDisplayname")
        self.gridLayout.addWidget(self.pushButtonModifyDisplayname, 4, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditModifyDisplayname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditModifyDisplayname.setEnabled(False)
        self.lineEditModifyDisplayname.setObjectName("lineEditModifyDisplayname")
        self.gridLayout.addWidget(self.lineEditModifyDisplayname, 4, 2, 1, 1)
        self.lineEditModifyPswd = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditModifyPswd.setEnabled(False)
        self.lineEditModifyPswd.setObjectName("lineEditModifyPswd")
        self.gridLayout.addWidget(self.lineEditModifyPswd, 2, 2, 1, 1)
        self.lineEditEnterPswd = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditEnterPswd.setMaxLength(20)
        self.lineEditEnterPswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditEnterPswd.setObjectName("lineEditEnterPswd")
        self.gridLayout.addWidget(self.lineEditEnterPswd, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.pushButtonModifyPswd = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonModifyPswd.setEnabled(False)
        self.pushButtonModifyPswd.setObjectName("pushButtonModifyPswd")
        self.gridLayout.addWidget(self.pushButtonModifyPswd, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 1, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 3, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonModifyDisplayname.setText(_translate("Dialog", "Modify display name"))
        self.label.setText(_translate("Dialog", "Enter your password"))
        self.pushButtonModifyPswd.setText(_translate("Dialog", "Modify password"))
